### ISSUE TITLE
setup.py not working

### ISSUE THREAD

**Issue by Chris-Pedersen** [igmhub/cup1d#17]
When running setup.py the package finder cannot find the relevant modules, as they are one directory too deep. I get:

```
chris@chris-XPS:~/Testbed/cup1d$ python3 setup.py install --user
running install
running bdist_egg
running egg_info
creating cup1d.egg-info
writing cup1d.egg-info/PKG-INFO
writing dependency_links to cup1d.egg-info/dependency_links.txt
writing top-level names to cup1d.egg-info/top_level.txt
writing manifest file 'cup1d.egg-info/SOURCES.txt'
writing manifest file 'cup1d.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
```

There are a few potential ways to fix this, the simplest is to just move the `cupid` out of the `py` directory. An alternative would be to add some extra information to `setup.py` rather than use `find_packages()`, which doesn't locate the files in the current set up. I've added a PR with the first approach, but happy to explore other options if you prefer!

**Comment by andreufont** [comment]
Closed in #18
