### ISSUE TITLE
Add option to add random noise to the mocks using the covariance matrix

### ISSUE THREAD

**Issue by andreufont** [igmhub/cup1d#24]
We are currently generating a noiseless mock P1D, in the sense that we set the mock data vector to the one from a simulation (or from a model once #23 is implemented).

It would be useful to be able to generate a random draw from the covariance matrix, and add the fluctuations to the smooth model.

**Comment by jchavesmontero** [comment]
@andreufont Is this already implemented? If not, I could work on this

**Comment by andreufont** [comment]
It is not implemented. Please go ahead!
